apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhel9-soe-datavolume
  namespace: openshift-virtualization-os-images 
spec:
  source:
    registry:
      url: "docker://quay.io/virt-corp/rhel9-soe:latest"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 30Gi
