---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleWorkflow
metadata:
  name: rhel9-gitops1-1
  namespace: aap
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  connection_secret: controller-access-admin
  workflow_template_name: "gitops-post-config"
  inventory: virtcluster # Inventory prompt on launch needs to be enabled

  vars: # Extra variables prompt on launch needs to be enabled
    vm_name: rhel9-gitops1-1
