---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  Name: ansible-job 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  connection_secret: controller-access-admin
  job_template_name: "gitops-post-config"
  inventory: virtcluster # Inventory prompt on launch needs to be enabled

  extra_vars: # Extra variables prompt on launch needs to be enabled
    vm_name: "$(VM_NAME)"
