- name: Listen for Machine resource events
  hosts: localhost

  sources:
  - sabre1041.eda.k8s:
      api_version: kubevirt.io/v1
      kind: VirtualMachineInstance
      namespace: 00-system1

  rules:
    - name: Run Job on VM start
      condition: 
        all:
        - event.type == 'MODIFIED'
        - event.resource.status.phase == 'Running'
        - event.resource.metadata.annotations.post-config-done is not defined- event.type == 'MODIFIED'
      action:
        run_workflow_template:
          name: gitops-post-config 
          organization: codell.io

        # 2) Then patch the VM with 'post-config-done' annotation
        #run_job_template:
        #  name: add_post_config_annotation.yaml
          # pass info from the event if needed
        #  extra_vars:
        #    vm_namespace: "{{ event.resource.metadata.namespace }}"
        #    vm_name: "{{ event.resource.metadata.name }}" 
        debug: